### ISSUE TITLE
name in i18n not match with english file.

### ISSUE THREAD

**Issue by likyh** [merico-dev/lake-website#104]
![image](https://user-images.githubusercontent.com/3294100/177257236-59a0b234-84ee-4e3e-b2f5-1803e55be431.png)

**Comment by nikitakoselev** [comment]
Can you provide some description?

**Comment by likyh** [comment]
> Can you provide some description?

![image](https://user-images.githubusercontent.com/3294100/177676652-42bccadf-bf1c-403d-8efe-ed282c5e65b6.png)
It should match one by one to activate i18n.

**Comment by yumengwang03** [comment]
We will only maintain the English docs/blogs from now.
