### ISSUE TITLE
[Doc][Installation] Update Docs for new version with some minor fix

### ISSUE THREAD

**Issue by Palanikannan1437** [merico-dev/lake-website#160]
## Documentation Scope

For v0.12.0, we can provide improved docs to avoid errors regarding **File Permissions** while installing via the docker-compose method!

## Describe the Change

- Adding a **NOTE** for the users installing the tool via the docker-compose method in the [Launch DevLake](https://devlake.apache.org/docs/QuickStart/DockerComposeSetup/#launch-devlake) section 
- To check file permissions **before** executing the `docker-compose up -d` command to avoid errors!

Slack conversion thread: https://devlake-io.slack.com/archives/C03APJ20VM4/p1660281081774489

**Comment by yumengwang03** [comment]
Hi, @ppborah and @Palanikannan1437, I saw that on the other issue that you guys would like to work on this issue. Is that correct? :)

**Comment by Palanikannan1437** [comment]
Hey @yumengwang03, not sure how I missed this...thanks a ton for assigning it to me, I'll work on this asap!
