### ISSUE TITLE
[Doc][Dev-Installation] Update Docs for Installing libgit2 with MacPorts 

### ISSUE THREAD

**Issue by Palanikannan1437** [merico-dev/lake-website#163]
## Documentation Scope

For v0.12.0, while setting up the dev environment, we can provide improved docs to avoid errors while installing libgit2 via MacPorts/Brew since they don't support libgit2 v1.3.0 which is currently required to build the application.

## Describe the Change

- Adding a **NOTE** for the users installing the tool via Macports/Brew method in the [Installing RefDiff Plugin](https://devlake.apache.org/docs/Plugins/refdiff#macos) section for MacOS to use `Installing via Source` instead!

Slack conversion threads:
- https://devlake-io.slack.com/archives/C03APJ20VM4/p1660657370581859
- https://devlake-io.slack.com/archives/C03APJ20VM4/p1660707790863229

**Comment by warren830** [comment]
Hi @Palanikannan1437 , we already updated the doc, thanks for your suggestion!
