### ISSUE TITLE
Update the title for Architecture.md

### ISSUE THREAD

**Issue by Startrekzky** [merico-dev/lake-website#188]
## Document Scope
https://devlake.apache.org/docs/Overview/Architecture

## Describe the Change
change the title 'Architecture Overview' to 'Overview'.

## Screenshots
![image](https://user-images.githubusercontent.com/14050754/187947703-e2b09c2e-61b6-4507-bbfa-b473af331f79.png)

**Comment by mappjzc** [comment]
merged by #190
