### ISSUE TITLE
[Bug] Problems about DevLake website homepage responsiveness 

### ISSUE THREAD

**Issue by yumengwang03** [merico-dev/lake-website#213]
For the new homepage, there are a few responsiveness issues on screens of different size. A few bugs are listed below, but it would also be great if we can double check the display on different screen width.

On small desktop screens:
<img width="1388" alt="Screen Shot 2022-09-16 at 9 52 29 AM" src="https://user-images.githubusercontent.com/9535430/190969302-9645a4ea-dc4a-4890-8ec8-1ed78c5760de.png">

On very wide screens:
![Screen Shot 2022-09-19 at 10 32 22 AM](https://user-images.githubusercontent.com/9535430/190969292-29cae06f-3915-47bb-8eff-e9fa80ba523d.png)
![Screen Shot 2022-09-19 at 10 32 58 AM](https://user-images.githubusercontent.com/9535430/190969310-56029509-7f4a-42f7-a6a1-3762c6ffd4ac.png)

**Comment by henit-chobisa** [comment]
Let me get my hands on it! 🔥

**Comment by ghost** [comment]
@yumengwang03 Assign this to @henit-chobisa , our community member!
