### ISSUE TITLE
Domain Layer Schema diagram cannot be enlarged to view

### ISSUE THREAD

**Issue by yumengwang03** [merico-dev/lake-website#215]
On this page: https://devlake.apache.org/docs/DataModels/DevLakeDomainLayerSchema

<img width="1663" alt="Screen Shot 2022-09-20 at 6 17 42 PM" src="https://user-images.githubusercontent.com/9535430/191233386-71c75130-af01-4aad-ae2e-159192a740af.png">

**Comment by yumengwang03** [comment]
Additionally, it would be great if we can enable this enlarge feature for all images on the website.

**Comment by joneskj55** [comment]
May I be assigned to this? @Startrekzky @yumengwang03

**Comment by yumengwang03** [comment]
> May I be assigned to this? @Startrekzky @yumengwang03

Of course! Thank you for the interest!
