### ISSUE TITLE
Inconsistent Left and Right Margin on the Homepage

### ISSUE THREAD

**Issue by yumengwang03** [merico-dev/lake-website#226]
As shown in the screenshots below, the different sections of the Homepage have different left and right margins with certain screen width. All sections, except for The Header and Supported Data Sources sections, should be the same width. The screenshots are just some examples, and it would be great to check different breakpoints for consistensy.

<img width="649" alt="Screen Shot 2022-09-28 at 7 23 10 PM" src="https://user-images.githubusercontent.com/9535430/192767330-90251258-88e7-4963-a912-83e37e2a07a1.png">
<img width="389" alt="Screen Shot 2022-09-28 at 7 23 32 PM" src="https://user-images.githubusercontent.com/9535430/192767347-066e6e83-7caa-4dde-af3d-883bb0628461.png">

**Comment by IsaacArnold** [comment]
Can you please assign this to me? I'd like to work on this.

**Comment by ghost** [comment]
Hey @IsaacArnold thanks! I guess @henit-chobisa has tried to fix the issue.

You may pick other issues or create GFIs so we can look through it.
