### ISSUE TITLE
Update the status of the data sources on the Roadmap doc

### ISSUE THREAD

**Issue by yumengwang03** [merico-dev/lake-website#228]
On the [Roadmap doc](https://devlake.apache.org/docs/Overview/Roadmap), the first category of the table contains all data sources we would like to support this year. However, some of them have issues created already; some do not. The status of the ones with issues created might also be outdated.

It would be great to:
1. Check the data sources with issues created, and if the issues are close, updated the text from "open" to "closed"
2. If there is no issue created for a particular plugin, create one for it in DevLake's main repo's [issue tracker](https://github.com/apache/incubator-devlake/issues), and follow the template like [this](https://github.com/apache/incubator-devlake/issues/1883). You can also look at other issues for reference.

<img width="958" alt="Screen Shot 2022-09-28 at 7 38 06 PM" src="https://user-images.githubusercontent.com/9535430/192769440-b1b2a7fb-3891-47ec-b820-90e2e461f841.png">

**Comment by Azahar002** [comment]
Hy I would like to work on this, can you assign this to me ..!

**Comment by Azahar002** [comment]
Hy I am unable to find the Roadmap doc in repo, can someone please tell where can I find it. 
( This is going to be my first contribution, Please help me, Thanks )

**Comment by klesh** [comment]
@Azahar002 https://github.com/apache/incubator-devlake-website/blob/main/docs/Overview/Roadmap.md

**Comment by ankitmalakar7** [comment]
I have already given a PR with
1. Checked all data sources & updated already existing issues status with the latest as per the main repo.
2. Created new issues in DevLake's main repo for some particular plugins.

Kindly review the PR. @yumengwang03 @klesh @Startrekzky

**Comment by Startrekzky** [comment]
> I have already given a PR with
> 
> 1. Checked all data sources & updated already existing issues status with the latest as per the main repo.
> 2. Created new issues in DevLake's main repo for some particular plugins.
> 
> Kindly review the PR. @yumengwang03 @klesh @Startrekzky

Thanks @ankitmalakar7 . PR #264 has been merged.
