### ISSUE TITLE
Build a new live demo page for the website

### ISSUE THREAD

**Issue by yumengwang03** [merico-dev/lake-website#240]
We want to move the Live Demo section out of Docs as a separate section on the main menu. The style of the page will be the same as the Docs and Community pages, with a sidebar. The purpose of this is to make the live demo dashboards more visible.

Please note: The new Live Demo pages should be React pages, instead of markdown pages, like Docs and Community, so that we can add more interesting things later on.

The changes:
<img width="1665" alt="Screen Shot 2022-09-14 at 3 58 30 PM" src="https://user-images.githubusercontent.com/9535430/194712886-d53ee8e4-2e00-4869-97a9-8431eb7549f8.png">

What it should look like:
<img width="1280" alt="Live Demo" src="https://user-images.githubusercontent.com/9535430/194712896-846f039d-af94-490e-9ae6-7d7302107218.png">

**Comment by ghost** [comment]
Hey @yumengwang03 - Could you please add "hacktoberfest" label to this issue?

**Comment by Bivas-Biswas** [comment]
This looks really interesting, can I work on this ??

**Comment by yumengwang03** [comment]
> This looks really interesting, can I work on this ??

Yes of course! Thank you!
