### ISSUE TITLE
Error when executing npm install for the first time

### ISSUE THREAD

**Issue by mintsweet** [merico-dev/lake-website#257]
When I clone the project for the first time, it fails when I execute **npm install**.

![screenshot-20221014-101930](https://user-images.githubusercontent.com/37237996/195750511-0ee2c09c-a795-4210-9980-32bc4ed46b9a.png)

I think this is a bug specified by **mdx-mermaid** on version **1.2.3** for the version of the dependent library.

![screenshot-20221014-104708](https://user-images.githubusercontent.com/37237996/195750939-dad8d06b-28db-4b96-a849-68d98b90b0ea.png)

At the same time, I found that the package-lock.json file seems to have not been updated for a long time, although the npm package has changed.

So I will submit a PR to fix this.

**Comment by yumengwang03** [comment]
fixed in https://github.com/apache/incubator-devlake-website/pull/258
