### ISSUE TITLE
Bug: dropdown active state not working in other router state

### ISSUE THREAD

**Issue by Bivas-Biswas** [merico-dev/lake-website#268]
### Current Behavior:
![image](https://user-images.githubusercontent.com/75929842/195957885-335a1d55-aaaf-4d4c-9903-e1925d0b2030.png)

### Expected Behavior:
![image](https://user-images.githubusercontent.com/75929842/195957802-1355553a-b080-45d8-898e-4627d56c2213.png)

**Comment by Bivas-Biswas** [comment]
Hey @yumengwang03, I already fixed it.
can you add hacktoberfest tag?
so I can send a pr.

**Comment by yumengwang03** [comment]
> Hey @yumengwang03, I already fixed it. can you add hacktoberfest tag? so I can send a pr.

Sorry for the late reply. I've added the label. Please send a PR. This is a good catch!
