### ISSUE TITLE
Change the width of the iframe in the live demo

### ISSUE THREAD

**Issue by yumengwang03** [merico-dev/lake-website#271]
For the Live demo page, we want to make the following change: 
<img width="1655" alt="Screen Shot 2022-10-17 at 5 35 03 PM" src="https://user-images.githubusercontent.com/9535430/196193321-6ef192b7-a9f9-48ae-8994-3cbce5c1b237.png">

**Comment by 20RitikSingh** [comment]
I want to work on this.

**Comment by mindlesscloud** [comment]
> I want to work on this.

I have assigned it to you, good luck!

**Comment by yumengwang03** [comment]
@20RitikSingh  Sorry I just saw your comment. I made the iframe width to 135% (in this PR https://github.com/apache/incubator-devlake-website/pull/281) so that it's wider now. But probably there's a better way to do this?

**Comment by ankitmalakar7** [comment]
@yumengwang03 That's the best way to change its width what I think bcz docusaurus set a cut off of max-width after 997px, we can't change the width of the container itself, so your commit is perfect I think.
