### ISSUE TITLE
Graph data not Responsive in Live Demo Page

### ISSUE THREAD

**Issue by ankitmalakar7** [merico-dev/lake-website#279]
### **Now:**

![devlake issue](https://user-images.githubusercontent.com/84442212/196463186-5c30d495-c751-4536-9675-4569f6a2e089.jpg)

Graph data are overlapped & not being readable for mobile users.

**Comment by mindlesscloud** [comment]
Thank you for your valuable feedback, we will work on it

**Comment by yumengwang03** [comment]
This is problem with the embedded Grafana iframe, so we can't really do anything about it. How about we just display something like "For best viewing experience, pleases view the dashboard on a desktop"?

**Comment by ankitmalakar7** [comment]
@yumengwang03 Gave a PR with your suggested warning only for the mobile users. On desktop view, users will not face any warning & it will be same. Kindly review the PR.

**Comment by Startrekzky** [comment]
> @yumengwang03 Gave a PR with your suggested warning only for the mobile users. On desktop view, users will not face any warning & it will be same. Kindly review the PR.

PR https://github.com/apache/incubator-devlake-website/pull/286 has been merged. Thanks for your contribution.
