### ISSUE TITLE
[Doc][Metrics] Improve metric description in the Metrics page

### ISSUE THREAD

**Issue by iamppborah** [merico-dev/lake-website#301]
## Documentation Scope
https://devlake.apache.org/docs/next/Metrics

## Describe the Change
The tiles in the above 'Metrics' page does not contain a proper description. We should include proper description below the titles
For ex: 'PR Coding Time' has the same description 'PR Coding Time'. We should change it to something like: 'Time it takes from the first commit until a PR is issued'

## Additional context
Hey @yumengwang03 , could you please attach the 'Hacktoberfest' label here ?

**Comment by Startrekzky** [comment]
Cool. Label added. Can you paraphrase the issue title to "Improve metric description in the Metrics page" or something similar?

**Comment by iamppborah** [comment]
Done!

**Comment by Startrekzky** [comment]
Thanks @ppborah . Next time you can add 'closes {issue_number}' in your PR description, then the issue will be closed automatically after the PR gets merged.

**Comment by iamppborah** [comment]
> Done!

Hey @Startrekzky, you asked for the title change, "Done!" was in reply to that.
I opened this good first issue for our new community members. But, haven't received any updates till now. Will take it myself.

**Comment by Startrekzky** [comment]
Cool @ppborah , I updated the metrics page recently. Please pull the latest code before you make the changes.

**Comment by iamppborah** [comment]
Sure!
