### ISSUE TITLE
[Bug][Homepage] Logs gets distorted 

### ISSUE THREAD

**Issue by pottekkat** [merico-dev/lake-website#335]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake-website/issues?q=is%3Aissue) and found no similar issues.

### What happened

At this window size, the logos are distorted, as shown below:

![Screenshot 2022-12-01 at 10 06 33 AM](https://user-images.githubusercontent.com/49474499/204966911-b3040343-6106-4ee3-8605-a804b7619572.png)

If I increase the width of the window or decrease the width of the window, it looks fine.

This section is also not centered and there is a horizontal scroll with the same window size:

![Screenshot 2022-12-01 at 10 10 29 AM](https://user-images.githubusercontent.com/49474499/204967188-3a6b0dc2-ce84-44dd-ab6a-858bd64eed86.png)

### What do you expect to happen

1. The logos should not be distorted.
2. Everything should be centered.
3. No horizontal scroll.

### Version

main

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by mappjzc** [comment]
Thank you for your suggestion.
Are you willing to submit PR?

**Comment by pottekkat** [comment]
@mappjzc I'm very bad at this. Please assign this to someone else. Maybe a "good first issue".

**Comment by mappjzc** [comment]
> @mappjzc I'm very bad at this. Please assign this to someone else. Maybe a "good first issue".

Thanks for your report, we will follow up on this issue.
