### ISSUE TITLE
[Doc][Logs] Add user docs for downloading pipeline logs

### ISSUE THREAD

**Issue by keon94** [merico-dev/lake-website#341]
## Documentation Scope
User manuals -> Config UI

## Describe the Change
Add instructions on how pipeline execution logs can be downloaded.

## Screenshots
n/a

## Additional context
n/a

**Comment by kelvinparmar** [comment]
@keon94 In this issue what I have to do?
Please share about it so I can contribute

**Comment by keon94** [comment]
@kelvinparmar The doc simply has to mention that blueprint execution runs' logs can be found here:

![image](https://user-images.githubusercontent.com/25063936/210623621-0ba85708-a32b-4bcd-9386-f52afb52e0ca.png)

**Comment by kelvinparmar** [comment]
For that I have to make another file or where I have to mention about that ?

**Comment by kelvinparmar** [comment]
@yumengwang03 Please give back reply So I will work on it

**Comment by yumengwang03** [comment]
> @yumengwang03 Please give back reply So I will work on it

Thanks for your interest! I think you can just add a section of this info to this doc: https://devlake.apache.org/docs/UserManuals/ConfigUI/Tutorial

**Comment by kelvinparmar** [comment]
This issue is completed or not ? @yumengwang03

**Comment by yumengwang03** [comment]
> This issue is completed or not ? @yumengwang03

Yes, it's completed.

**Comment by keon94** [comment]
Where's the PR for this?
