### ISSUE TITLE
Lack of documentation for swagger

### ISSUE THREAD

**Issue by klesh** [merico-dev/lake-website#38]
Due to PR https://github.com/apache/incubator-devlake/pull/1900/files had been merged.
Documentation should be updated as well.

**Comment by ghost** [comment]
Can we add "hacktoberfest" tag to this one?

**Comment by klesh** [comment]
This requires knowledge of how the API works, it depends, how long does the participant have for solving the problem at scene?

**Comment by Startrekzky** [comment]
It's done. Please check it out https://devlake.apache.org/docs/DeveloperManuals/DeveloperSetup#using-devlake-api
