### ISSUE TITLE
[Doc][Manual] Add documentation for local Jenkins setup

### ISSUE THREAD

**Issue by keon94** [merico-dev/lake-website#385]
## Documentation Scope
Developer manuals

## Describe the Change
We need some docs for developers to get a local instance of Jenkins going via Docker. This is to be able to run the Jenkins plugins on their machines without having an actual Jenkins server available somewhere.

**Comment by Startrekzky** [comment]
May I ask why a developer needs this?

**Comment by keon94** [comment]
> May I ask why a developer needs this?

@Startrekzky a user in Slack was recently struggling to get their Jenkins instance to work with Devlake, so we figured we add some docs for a local Jenkins to make troubleshooting/recreating issues easier on our side. cc @hezyin

**Comment by Startrekzky** [comment]
@keon94 Got it. This seems to be a rare use case, but feel free to add some docs.
