### ISSUE TITLE
[Doc][components/Team, Home page] Dark theme not getting enabled on Team & Home page

### ISSUE THREAD

**Issue by aparna2071** [merico-dev/lake-website#386]
## Documentation Scope
This is for home/index page & Team page.

## Describe the Change
There is a theme toggler which enables us to toggle between light and dark modes. 
It is working as expected for all pages except Home page & Team page.

## Screenshots
- This is what is expected when toggled to dark mode(currently working properly for all other pages except Home & Team):
![dark_apache_expected](https://user-images.githubusercontent.com/54634804/211652325-81a398a6-606d-4a31-87aa-85e9959f321f.PNG)

- This is what is currently for Home & Team pages (in Dark theme):
![dark_apache_current](https://user-images.githubusercontent.com/54634804/211652701-763ba775-8d88-406b-b7ae-b0da2287a1b2.PNG)

## Additional context
As is clear from the screenshot, the dark theme is not getting enabled properly for some pages.
I'm trying to create a PR to fix this but not able to do so, will need some help probably.

**Comment by Startrekzky** [comment]
Hi @aparna2071 , thanks for the proposal. I'm sorry that the homepage and team pages will not support dark mode in a short time, as all the images, font-type, and CSS styles need to be supported in the dark mode. This requires a lot of efforts and the benefits are not clear (from my perspective). Thus, I suggest postponing this feature.

**Comment by aparna2071** [comment]
Thank you so much @Startrekzky for your reply.
