### ISSUE TITLE
[Doc][Sections\HomepageHeader.tsx] Links to Companies that trust Devlake are missing

### ISSUE THREAD

**Issue by aparna2071** [merico-dev/lake-website#389]
## Documentation Scope
This is for Home page

## Describe the Change
The "Trusted by" companies don't have links to their sites. 
I want to add links of those companies, so that users who are not aware of the companies can get a idea of those.

## Screenshots
- Current website:
![apache_trusted_before](https://user-images.githubusercontent.com/54634804/212162094-5fb4d634-b75c-4375-8518-bcad804851b3.PNG)

- What I want to add: I want to make the "Trusted by" companies clickable & on click, it should redirect to their links.
Could not capture screenshot of the same

**Comment by kelvinparmar** [comment]
Yeah @aparna2071 that's nice issue when users come to see which company are sponsor to apache devlake it's directly go through this home page

**Comment by aparna2071** [comment]
> Yeah @aparna2071 that's nice issue when users come to see which company are sponsor to apache devlake it's directly go through this home page

Yes @kelvinparmar 
Thanks 👍
