### ISSUE TITLE
[Doc][README.md] Steps to create a PR are missing in README.md

### ISSUE THREAD

**Issue by aparna2071** [merico-dev/lake-website#411]
## Documentation Scope
This is for README.md file

## Describe the Change
The steps to create a PR are missing in README.md which makes it difficult for a beginner in open source to contribute to this project. That's why I want to add the steps to create PR to make it more readable & understandable by beginners.

## Screenshots
If applicable, add screenshots to help explain your thoughts.

**Comment by Startrekzky** [comment]
You can update the example in this doc: https://devlake.apache.org/community/make-contribution/development-workflow/. Then add the link to the README.

For example: change the repo name as below
![image](https://user-images.githubusercontent.com/14050754/215650415-b684ce6f-7284-4190-869d-d03f67139371.png)
