### ISSUE TITLE
[Doc][Use Cases] link to broken page in DORA use case

### ISSUE THREAD

**Issue by Ushuaiaff** [merico-dev/lake-website#436]
## Documentation Scope
[DORA use case](https://devlake.apache.org/livedemo/EngineeringLeads/DORA) now has a link to broken page. 

## Describe the Change
redirect to [docs](https://devlake.apache.org/docs/next/DORA).

## Screenshots
If applicable, add screenshots to help explain your thoughts.
![image](https://user-images.githubusercontent.com/55527719/218924665-206dc064-d6ea-429a-a7e7-b1f851669a0a.png)

**Comment by Startrekzky** [comment]
Thanks @Ushuaiaff , I'll fix it.
