### ISSUE TITLE
Minor issues on website homepage

### ISSUE THREAD

**Issue by hezyin** [merico-dev/lake-website#47]
![screencapture-devlake-apache-org-2022-05-25-14_54_26](https://user-images.githubusercontent.com/2908155/170379133-28c34209-e1a9-4d3c-97c5-8f423017e608.png)

1. Some users may not be familiar with the term SDLC, I suggest we expand the abbreviation the first time we mention it: SDLC -> Software Development LifeCycle (SDLC)
2. There's a typo in `series`. Maybe the sentence can be shortened to "Visualize out-of-the-box engineering metrics in a series of use-case driven dashboards"
3. Maybe we can be a bit more concrete for users with: Easily extend DevLake to support your data sources, metrics, and dashboards
4. The two `Docs` look a bit weird
5. The GitHub link right now points to a fork, not the `apache/incubator-devlake` repo.

**Comment by nikitakoselev** [comment]
The abovementioned issues look resolved, please close the ticket
![image](https://user-images.githubusercontent.com/6383738/171796631-79097a07-97ac-4888-8a68-c6c79abb61d3.png)

**Comment by klesh** [comment]
@hezyin Please confirm they were all fixed and close the issue?

**Comment by yumengwang03** [comment]
Already fixed.
