### ISSUE TITLE
[Doc][Azure] Document Azure DevOps

### ISSUE THREAD

**Issue by Startrekzky** [merico-dev/lake-website#500]
## Documentation Scope

- [ ] add a plugin doc here with the name 'Azure DevOps(Beta)': https://devlake.apache.org/docs/Plugins.
- [ ] add a manual doc here with the name 'Azure DevOps(Beta)': https://devlake.apache.org/docs/Configuration/Tutorial

Please follow the doc structure for other plugin docs and manuals.

**Comment by CamilleTeruel** [comment]
I take it.
