### ISSUE TITLE
[Doc][DeveloperManuals] PluginImplementation

### ISSUE THREAD

**Issue by tim-goto** [merico-dev/lake-website#523]
## Documentation Scope
[This image](https://i.imgur.com/itzlFg7.png) (defined [here](https://github.com/apache/incubator-devlake-website/blob/main/docs/DeveloperManuals/PluginImplementation.md?plain=1#L111)) in the Developer Manuals - Plugin Implementation does not show up and only displays an error message when opened directly

## Describe the Change
Please update the image and image link.

Edit: Also [this](https://i.imgur.com/tkDuofi.png) and several other images on this page seem to be broken

**Comment by klesh** [comment]
plugin generator is broken and yet to be fixed.

**Comment by tim-goto** [comment]
Does the plugin generator also create the images that are referenced here or do the images show a state that is not reflecting the current state of the generator or its broken state?

**Comment by tim-goto** [comment]
The images seem to be fixed now.. Maybe that was just an error on imgurs side..
