### ISSUE TITLE
[Doc] The meaning of "data scope" is unclear

### ISSUE THREAD

**Issue by asterix314** [merico-dev/lake-website#537]
In _Overview_, the concept of the "data scope" is not clearly explained. After consulting @klesh, I now know it's something like "a generalization of the top-level objects in various DevOps tools. Examples include JIRA boards, GitLab projects, and GitHub Repos"..

In the domain layer schema document, some "data scope" related tables (`cicd_scopes` and `project_mapping`) and fields may be clarified also.

**Comment by klesh** [comment]
Thanks for the suggestion, much appreciated.
