### ISSUE TITLE
[Doc] Make 'supported data sources' information more accessible

### ISSUE THREAD

**Issue by Startrekzky** [merico-dev/lake-website#580]
## Documentation Scope
- [ ] All docs in this folder: https://devlake.apache.org/docs/Plugins
- [ ] Homepage: https://devlake.apache.org/

## Describe the Change
- Add a section called `Supported Versions` to each plugin's detail page 
![image](https://github.com/apache/incubator-devlake-website/assets/14050754/49bd44f5-1cf7-49d2-8ea8-f5dc2302740e)

- Update the wordings and link at the supported data sources section on the [homepage](https://devlake.apache.org/)
![image](https://github.com/apache/incubator-devlake-website/assets/14050754/d5ef49a0-7530-4e12-933f-6f521101bd15)

**Comment by ghost** [comment]
@Startrekzky please assign this to me

**Comment by anjy7** [comment]
Hey @Startrekzky @JoshuaPoddoku , may I work on this issue?

**Comment by ghost** [comment]
Hey @Startrekzky please review this PR: https://github.com/apache/incubator-devlake-website/pull/592
