### ISSUE TITLE
[Doc][Setup/FAQs] Document that Dynatrace must be disabled

### ISSUE THREAD

**Issue by keon94** [merico-dev/lake-website#589]
As seen in https://github.com/apache/incubator-devlake/issues/5612, Dynatrace seems to be problematic in cloud environments and cause crashes. It must be disabled/not-installed. Document this.

**Comment by jdaemon7** [comment]
https://community.dynatrace.com/t5/Container-platforms/Oneagenthelper-process-for-Docker/m-p/176056
