### ISSUE TITLE
[Doc][Introduction] Update introduction page

### ISSUE THREAD

**Issue by ghost** [merico-dev/lake-website#593]
Planning to update the [introduction page](https://devlake.apache.org/docs/next/Overview/Introduction) in docs as it is been a while. cc: @hezyin @Startrekzky 

Here's the draft for the introduction: [PDF](https://github.com/apache/incubator-devlake-website/files/12114627/e.pdf)

**Comment by Startrekzky** [comment]
Hi @JoshuaPoddoku , what are the key differences between the new version and the old one?
