### ISSUE TITLE
[Bug][Homepage] Slack url is not working

### ISSUE THREAD

**Issue by ghost** [merico-dev/lake-website#608]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake-website/issues?q=is%3Aissue) and found no similar issues.

### What happened

![Screenshot 2023-07-28 at 12 01 14 AM](https://github.com/apache/incubator-devlake-website/assets/31725457/78f709fc-d294-4c46-89a8-4952e6ede4eb)

### What do you expect to happen

Slack link must be updated / fixed

### Version

main

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by rbutoi** [comment]
The new URL seems to be not working
