### ISSUE TITLE
Update document for https://github.com/apache/incubator-devlake/pull/2053

### ISSUE THREAD

**Issue by klesh** [merico-dev/lake-website#63]
To be updated
- Developer setup: to install `mockery` for running local unit test
- Document of testing
  1. Test categories: unit-test / e2e-test / integrated test
  2. How to write unit-test
  3. How to write e2e-test for plugin
  4. How to write integration test
- Update <How to contribute plugin>, to add a link to the testing document

**Comment by kelvinparmar** [comment]
Hey @klesh what have to do in this task ? Please explain

**Comment by klesh** [comment]
@kelvinparmar 
It has been a while since I created the issue, and most of them were fixed. I checked and here are some missing part:

1. how to write unit-tests - writing unit test is a common technique, we may link to some publicly available articles directly or compose our own based on those articles. PS. I recommend using `github.com/stretchr/testify/assert` as the assertion library.
2. how to write integration-tests - We never put too many resources in this apartment, so I think we can skip this part for now.
3. add links to How to write UnitTest/E2E-test/IntegrationTest in "Developer Setup"

Hopefully, that answered your question.

**Comment by kelvinparmar** [comment]
But in which file I have to write this test?

**Comment by klesh** [comment]
@kelvinparmar 
for `unit-test`, i think we need to create a new page for it. under the **Developer Manuals** section

**Comment by klesh** [comment]
we can skip the integration-test.
and "Developer Setup" already exists in the **Developer Manuals** section, we just need to add links into the article.

**Comment by kelvinparmar** [comment]
Hey @klesh In Unit test what I have to write unit test any suggestions for that?

**Comment by kelvinparmar** [comment]
@yumengwang03 have you any idea about this one?

**Comment by klesh** [comment]
> any suggestion

I think for the first section of the document could be a simple introduction and links to other articles of "How to write UnitTest for golang":

- [Add a test - The Go Programming Language](https://go.dev/doc/tutorial/add-a-test)
- [How To Write Unit Tests in Go | DigitalOcean](https://www.digitalocean.com/community/tutorials/how-to-write-unit-tests-in-go-using-go-test-and-the-testing-package)

In the next section, we can add links to some of our test-case source file.

- [incubator-devlake/migrator_test.go at 243cc8a80aa5b37828e2a142ac9f7e3269b7e1dc · apache/incubator-devlake](https://github.com/apache/incubator-devlake/blob/243cc8a80aa5b37828e2a142ac9f7e3269b7e1dc/backend/core/migration/migrator_test.go)


Lastly, we may declare that we prefer to use the following libraries to write unit tests:

- "github.com/stretchr/testify/assert"
- "github.com/stretchr/testify/mock"
