### ISSUE TITLE
[Doc][Plugin] Explicitly describe how incidents are related to deployments via webhook plugin

### ISSUE THREAD

**Issue by nathan-nicholson** [merico-dev/lake-website#644]
## Documentation Scope

This would be specific to the Webhook Plugin doc.

## Describe the Change

The documentation describe how incidents that are pushed to the webhook relate to deployments reported by the webhook. Specifically, that they are related by time and how that impacts how webhooks are created and utilized.

Currently, it is not currently called out that incidents and deploys are related purely by timestamp comparison. This can lead to confusion when someone begins reporting deployments by a single webhook  and realizes that incidents cannot be reliably reported that way.

## Screenshots
If applicable, add screenshots to help explain your thoughts.

## Additional context

I specifically ran into this problem and am having to adjust my data collection accordingly. Hoping to spare anyone else the same fate. 😅

**Comment by clement-igonet** [comment]
Could you tell where the relation between incident and deployment is explained in the docs ?

**Comment by d4x1** [comment]
@clement-igonet Does this https://devlake.apache.org/docs/Plugins/webhook help?
