### ISSUE TITLE
[Bug] "Trusted By" company icons should redirect to the company page in new tab for better user experience

### ISSUE THREAD

**Issue by dheerajsingh89** [merico-dev/lake-website#705]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake-website/issues?q=is%3Aissue) and found no similar issues.

### What happened

As shown in below videos , When we click on the companies icons then it will redirect to the companies page in same tab that is not good for better user experience.

[enhancement_required.webm](https://github.com/apache/incubator-devlake-website/assets/107138786/93b1edda-dee3-422f-8d66-23b6dc131d8a)

### What do you expect to happen

When We click on the companies icon , it should redirect to the companies page in new tab for better user experience

### Version

main

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by mintsweet** [comment]
Hi @itsdheerajdp, thank you for your feedback and pr.
